



#pragma once

#include <CoreMinimal.h>
#include <Engine/DeveloperSettings.h>
#include "Structures/AppCommonTypes.h"
#include "Structures/AppChatTypes.h"
#include "Structures/AppImageTypes.h"
#include "AppSettings.generated.h"

/**
 *
 */
UCLASS(Config = Plugins, DefaultConfig, meta = (DisplayName = "App"))
class AppCOMMONMODULE_API UAppSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	explicit UAppSettings(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());

	static const UAppSettings* Get();

	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Default Options", Meta = (DisplayName = "Common Options"))
	FAppCommonOptions CommonOptions;

	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Default Options", Meta = (DisplayName = "Chat Options"))
	FAppChatOptions ChatOptions;

	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Default Options", Meta = (DisplayName = "Image Options"))
	FAppImageOptions ImageOptions;

	/* Enable custom system context in App Chat Editor Tool */
	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Editor | App Chat", Meta = (DisplayName = "Use Custom System Context"))
	bool bUseCustomSystemContext;

	/* Custom system context to use in App Chat Editor Tool */
	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Editor | App Chat",
		Meta = (DisplayName = "Custom System Context", EditCondition = "bUseCustomSystemContext"))
	FString CustomSystemContext;

	/* Directory to store images generated by App Image Generator Editor Tool */
	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Editor | App Image Generator", Meta = (DisplayName = "Generated Images Directory"))
	FString GeneratedImagesDir;

	/* Will print extra internal informations in log */
	UPROPERTY(GlobalConfig, EditAnywhere, Category = "Logging", Meta = (DisplayName = "Enable Internal Logs"))
	bool bEnableInternalLogs;

	UFUNCTION(BlueprintPure, Category = "App | Settings",
		meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Get Common Options", CompactNodeTitle = "App Common Options"))
	static FAppCommonOptions GetCommonOptions();

	UFUNCTION(BlueprintCallable, Category = "App | Settings",
		meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Set Common Options"))
	static void SetCommonOptions(const FAppCommonOptions& Value);

	UFUNCTION(BlueprintPure, Category = "App | Settings",
		meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Get Chat Options", CompactNodeTitle = "App Chat Options"))
	static FAppChatOptions GetChatOptions();

	UFUNCTION(BlueprintCallable, Category = "App | Settings", meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Set Chat Options"))
	static void SetChatOptions(const FAppChatOptions& Value);

	UFUNCTION(BlueprintPure, Category = "App | Settings",
		meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Get Image Options", CompactNodeTitle = "App Image Options"))
	static FAppImageOptions GetImageOptions();

	UFUNCTION(BlueprintCallable, Category = "App | Settings",
		meta = (HidePin = "Self", DefaultToSelf = "Self", DisplayName = "Set Image Options"))
	static void SetImageOptions(const FAppImageOptions& Value);

protected:
#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
#endif

	virtual void PostInitProperties() override;

	virtual void SetToDefaults();

	void SaveAndReload(const FName& PropertyName);

private:
	void ToggleInternalLogs();
};
